name: Release #
on:
  push:
    branches:
      - fix-workflow
jobs:
  release-action:
    runs-on: ubuntu-latest
    steps:
      - name: Release action
        uses: atomicfi/action-release-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
