name: Release
on:
  push:
    branches:
      - main
jobs:
  release-action:
    runs-on: ubuntu-latest
    steps:
      - name: Release action
        uses: atomicfi/action-release-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  
